name: CI
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events 
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os}}
    strategy:
      matrix:
        # The job will run on Linux, macOS, and Windows
        os: [ ubuntu-latest ]
        node: [14, 16]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - uses: codecov/codecov-action@v2
        with:
          files: ./coverage/clover.xml
          name: codecov-umbrella 
          verbose: true # optional (default = false) 


      # Runs a single command using the runners shell
      - name: Install dependencies
        run: npm install

      - name: Install development dependencies
        run: npm install --only=dev

      - name: Run tests
        run: npm test
